# -*- coding: utf-8 -*-
"""Regresión Linea - Varias Variables.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/159f_RX6gpRKVAYoAIEKqu4qgrB7fAxf0
"""

import pandas as pd

data = pd.read_csv('sample_data/Loan_Eligibility_1200.csv')

data.columns = [
    'ID_Cliente',
    'Genero',
    'Casado',
    'Dependientes',
    'Educacion',
    'Independiente',
    'Ingreso_Solicitante',
    'Ingreso_CoSolicitante',
    'Monto_Prestamo',
    'Plazo_Prestamo',
    'Historial_Credito',
    'Zona_Propiedad',
    'Estado_Prestamo'
]

data.describe()

data.head()

data.columns

data.info()

data['Estado_Prestamo'].value_counts()

data[data['Ingreso_Solicitante'] > data['Ingreso_Solicitante'].quantile(0.75)]

data['Genero_num'] = data['Genero'].map({'Female': 0, 'Male': 1})

subDF2 = data[['Ingreso_Solicitante',
             'Ingreso_CoSolicitante',
             'Dependientes',
             'Plazo_Prestamo',
             'Historial_Credito',
              'Genero_num',
             'Monto_Prestamo']]

matrix = subDF2.corr()
matrix

print(matrix['Monto_Prestamo'].sort_values(ascending=False))

"""Regresión Lineal"""

import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

reg = LinearRegression()

X = data[['Ingreso_Solicitante',
           'Ingreso_CoSolicitante',
           'Dependientes',
           'Plazo_Prestamo',
           'Historial_Credito',
           'Genero_num']]
y = data['Monto_Prestamo']

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2, random_state=42
)
reg.fit(X_train, y_train)
B0 = reg.intercept_
B = reg.coef_
nombres_vars = X.columns

print("\n===== COEFICIENTES DEL MODELO (ENTRENADO CON TRAIN) =====")
print("Intercepto B0:", B0)
for nombre, coef in zip(nombres_vars, B):
    print(f"B_{nombre}: {coef}")

ecuacion = "Monto_Prestamo = {:.3f}".format(B0)
for nombre, coef in zip(nombres_vars, B):
    ecuacion += " + ({:.6f} × {})".format(coef, nombre)
print("\nFunción del modelo:")
print("  " + ecuacion)

print("\n===== PREDICCIÓN MANUAL DE EJEMPLO =====")
ingreso_s = float(input("Digite Ingreso_Solicitante: "))
ingreso_co = float(input("Digite Ingreso_CoSolicitante: "))
depend    = float(input("Digite número de Dependientes: "))
plazo     = float(input("Digite Plazo_Prestamo: "))
hist      = float(input("Digite Historial_Credito (0 o 1): "))
genero_num = float(input("Digite Genero_num (0 = Femenino, 1 = Masculino): "))

# Mismo orden y mismos nombres que en X
cols = ['Ingreso_Solicitante',
        'Ingreso_CoSolicitante',
        'Dependientes',
        'Plazo_Prestamo',
        'Historial_Credito',
        'Genero_num']

x_nuevo_df = pd.DataFrame(
    [[ingreso_s, ingreso_co, depend, plazo, hist, genero_num]],
    columns=cols
)

monto_estimado = reg.predict(x_nuevo_df)[0]

print("Monto de préstamo estimado:", monto_estimado)

y_pred_test = reg.predict(X_test)
y_pred_train = reg.predict(X_train)

mse_test = mean_squared_error(y_test, y_pred_test)
mae_test = mean_absolute_error(y_test, y_pred_test)
r2_test = r2_score(y_test, y_pred_test)

print("\n===== MÉTRICAS EN TEST =====")
print("MSE test:", mse_test)
print("MAE test:", mae_test)
print("R² test:", r2_test)

mse_train = mean_squared_error(y_train, y_pred_train)
mae_train = mean_absolute_error(y_train, y_pred_train)
r2_train = r2_score(y_train, y_pred_train)

print("\n===== MÉTRICAS EN TRAIN =====")
print("MSE train:", mse_train)
print("MAE train:", mae_train)
print("R² train:", r2_train)

plt.figure(figsize=(6,6))
plt.scatter(y_test, y_pred_test, alpha=0.7, color='blue', label='Real vs Predicho')
min_val = min(y_test.min(), y_pred_test.min())
max_val = max(y_test.max(), y_pred_test.max())
plt.plot([min_val, max_val], [min_val, max_val], 'r--', label='Línea ideal y=x')
plt.xlabel('Monto_Prestamo real')
plt.ylabel('Monto_Prestamo predicho')
plt.title('Regresión múltiple: real vs predicho (test)')
plt.legend()
plt.grid(True)
plt.show()